### ISSUE TITLE
Altered the setup.sh file and added a line to grab the UUID of the SD card...

### ISSUE THREAD

**Issue by greatbeach** [ways/rpi-readonly#1]
I downloaded and ran the script on my new 2017-11-29-stretch install and it mostly worked...  errors and fixes below:

- Got an error on line 27 where it tries to move and rename /etc/resolv.conf...  just needed a space between the old and new file.
- Line 24 echos a string to '/boot/cmdline.txt' but contains a UUID that did not match mine...  I added the following to the script starting at line 24 and replacing the previous echo directive:
```
uuid=`grep '/ ' /etc/fstab | awk -F'[=]' '{print $2}' | awk '{print $1}'`
echo "dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=$uuid rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait noswap ro fastboot" > /boot/cmdline.txt
```
I hope this helps someone out there - your script was desperately need in my mind, thank you for putting it together in the first place!   :)

-Beach

**Comment by paulhayes** [comment]
Hi @ways. I hope you incorporate this fix. I was stumped until I found this report. The UUID being wrong caused my pi to not complete booting, and without error, so I completely lost.

**Comment by ways** [comment]
Thanks, will use your fixes once I get around to test them.

**Comment by ways** [comment]
Merged, thanks!
