### ISSUE TITLE
Make boot partition rw

### ISSUE THREAD

**Issue by paulhayes** [ways/rpi-readonly#2]
It's useful having a rw area, for debug purposes. Is there a way to keep the boot partition rw?

Oh and thanks for making these scripts and keeping them up to date. They are real lifesavers. I'm always hesitant to try scripts posted on forums, as they quickly go stale.

**Comment by ways** [comment]
Hi. /boot is the worst place to keep rw, as it's a FAT file system that breaks easily.

I use the command rw / ro to remount filesystem read/write or read only on demand. Or use tmpfs (/tmp /run etc). None of these work for your situation?

**Comment by paulhayes** [comment]
My situation is a little different. I very very occasionally need to write a short file with the current state, just in case of reboot. It only gets written to only very occasionally and not when it might power off. The /boot/ seemed the best place, without creating a separate partition for it. I know it's risky, but I'd like to give it a go. Any pointers?

I saw the rw/ro commands, there are great, I've been using them to switch back and force between development mode ( although I find I need to chmod +w the working directory after calling rw, but that's no hassle.
 
I think this utility is really useful for those of us making standalone iot devices using the raspberry pi zero. Thanks for the great work!

**Comment by ways** [comment]
Then I think the best solution for you is to do one of the following:
* create another partition on the SD card, and have that mounted RW.
* have a cronjob hourly run rw, sync file from tmpfs to disk, ro.

**Comment by ways** [comment]
Stalled. Reopen if you have new suggestions.

**Comment by paulhayes** [comment]
Hey @ways. Frustratingly I was having problems finding a way to repartitioning a pre existing raspbian primary boot partition. Which was a real shame. 

I ended up modifying your script to ignore the boot partition, to have it do this but I agree it's not the best solution.
